language: node_js
node_js:
  - "4"
  - "6"
  - "7"
env:
  - CXX=g++-4.8
matrix:
  fast_finish: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm -g install npm@latest
  - node --version
  - npm --version
  - cp -f .env_example .env
